# Generated by Django 4.1.7 on 2023-09-26 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("multiclique", "0002_update_meta"),
    ]

    operations = [
        migrations.RenameField(
            model_name="multicliqueaccount",
            old_name="public_keys",
            new_name="signatories",
        ),
        migrations.AddField(
            model_name="multicliqueaccount",
            name="name",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
