# Generated by Django 4.1.7 on 2023-09-28 11:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("multiclique", "0004_multiclique_signatory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="multicliquesignatory",
            old_name="public_key",
            new_name="address",
        ),
    ]
