# Generated by Django 4.1.7 on 2023-10-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("multiclique", "0006_transaction_updates"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="multicliqueaccount",
            name="policy",
        ),
        migrations.DeleteModel(
            name="MultiCliquePolicy",
        ),
        migrations.CreateModel(
            name="MultiCliquePolicy",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.CharField(max_length=256, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=256)),
                ("active", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "MultiClique Policy",
                "verbose_name_plural": "MultiClique Policies",
                "db_table": "multiclique_policies",
            },
        ),
        migrations.AddField(
            model_name="multicliqueaccount",
            name="policy",
            field=models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, to="multiclique.multicliquepolicy"),
        ),
        migrations.AlterField(
            model_name="multicliquetransaction",
            name="ledger",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="multicliquetransaction",
            name="nonce",
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="multicliquetransaction",
            name="preimage_hash",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
