# Generated by Django 4.1.7 on 2023-10-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("multiclique", "0008_clean_up_table_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="multicliquetransaction",
            name="xdr",
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddConstraint(
            model_name="multicliquetransaction",
            constraint=models.UniqueConstraint(
                fields=("call_func", "call_args", "multiclique_account", "executed_at"), name="unique_with_optional"
            ),
        ),
        migrations.AddConstraint(
            model_name="multicliquetransaction",
            constraint=models.UniqueConstraint(
                condition=models.Q(("executed_at", None)),
                fields=("call_func", "call_args", "multiclique_account"),
                name="unique_without_optional",
            ),
        ),
    ]
