# Generated by Django 4.1.7 on 2023-10-16 15:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("multiclique", "0009_update_transaction"),
    ]

    operations = [
        migrations.AddField(
            model_name="multicliquepolicy",
            name="context",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=128), default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="multicliquepolicy",
            name="name",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.RemoveField(
            model_name="multicliquepolicy",
            name="active",
        ),
    ]
