# Generated by Django 4.1.7 on 2023-10-24 12:51

import django.db.models.deletion
from django.db import migrations, models

import core.utils
import multiclique.models


class Migration(migrations.Migration):
    dependencies = [
        ("multiclique", "0010_update_multiclique_policy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="multicliquepolicy",
            name="context",
        ),
        migrations.AlterField(
            model_name="multicliqueaccount",
            name="policy",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="accounts",
                to="multiclique.multicliquepolicy",
            ),
        ),
        migrations.AlterField(
            model_name="multicliquepolicy",
            name="address",
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="multicliquesignature",
            name="signatory",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="signatures",
                to="multiclique.multicliquesignatory",
            ),
        ),
        migrations.CreateModel(
            name="MultiCliqueContract",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("address", models.CharField(max_length=128, primary_key=True, serialize=False)),
                ("limit", core.utils.BiggerIntField(max_length=1024, null=True)),
                ("already_spent", core.utils.BiggerIntField(max_length=1024, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ELIO_CORE", "elio core"),
                            ("ELIO_VOTES", "elio votes"),
                            ("ELIO_ASSET", "elio asset"),
                            ("UNKNOWN", "unknown"),
                        ],
                        default=multiclique.models.MultiCliqueContractType["UNKNOWN"],
                        max_length=32,
                    ),
                ),
                ("policies", models.ManyToManyField(related_name="contracts", to="multiclique.multicliquepolicy")),
            ],
            options={
                "verbose_name": "MultiClique Contract",
                "verbose_name_plural": "MultiClique Contracts",
                "db_table": "multiclique_contract",
            },
        ),
    ]
