# Generated by Django 4.1.7 on 2023-10-25 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("multiclique", "0011_multiclique_contract_and_updates"),
    ]

    operations = [
        migrations.AddField(
            model_name="multicliquetransaction",
            name="submitter",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_transactions",
                to="multiclique.multicliquesignatory",
            ),
        ),
    ]
