# Generated by Django 4.1.7 on 2023-08-01 12:49

from django.db import migrations, models

import core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_proposal_setup_complete"),
    ]

    operations = [
        migrations.AlterField(
            model_name="governance",
            name="proposal_token_deposit",
            field=core.utils.BiggerIntField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="governance",
            name="type",
            field=models.CharField(choices=[("MAJORITY_VOTE", "majority vote")], max_length=128, null=True),
        ),
    ]
