# Generated by Django 4.1.7 on 2023-08-02 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_add_min_threshold_configuration"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="address",
            field=models.CharField(default="", max_length=128),
            preserve_default=False,
        ),
    ]
