# Generated by Django 4.1.7 on 2023-08-08 10:24

from django.db import migrations

import core.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_add_asset_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="block",
            name="number",
            field=core.utils.BiggerIntField(editable=False, max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name="governance",
            name="min_threshold_configuration",
            field=core.utils.BiggerIntField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="governance",
            name="proposal_duration",
            field=core.utils.BiggerIntField(max_length=1024),
        ),
        migrations.AlterField(
            model_name="proposal",
            name="birth_block_number",
            field=core.utils.BiggerIntField(max_length=1024),
        ),
    ]
