# Generated by Django 4.1.7 on 2023-09-18 15:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_bigger_int_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="address",
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
