# Generated by Django 4.1.7 on 2023-10-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_alter_account_address"),
    ]

    operations = [
        migrations.RemoveField(model_name="asset", name="id"),
        migrations.AlterField(
            model_name="asset",
            name="address",
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
