from unittest.mock import Mock

from settings.settings import BASE_DIR

TESTING = True
CONFIG_SECRET = "much-secure"

MEDIA_URL = "/test-media/"
MEDIA_ROOT = BASE_DIR / "test-media"

AWS_STORAGE_BUCKET_NAME = None
AWS_S3_ACCESS_KEY_ID = None
AWS_S3_SECRET_ACCESS_KEY = None
AWS_S3_REGION_NAME = None

FILE_UPLOAD_CLASS = "core.file_handling.test.file_handler_mock"
CELERY_TASK_ALWAYS_EAGER = True
RETRY_DELAYS = [0]
SOROBAN_SERVER = Mock()
CORE_CONTRACT_ADDRESS = "CDLUQRW6EXSX4SPXC4WTC3SD5KZE2BHDKPMMKJR4FOPGED4NPKKZ4C4Q"
VOTES_CONTRACT_ADDRESS = "CAPYKFOCLMWWLZRHF65RNARHTMALMBNUPT3EITOEGRZ6TYSA3BV43WMV"
MULTICLIQUE_CONTRACT_ADDRESS = "CAXDXBQKQ43BV4DO5WFMOIR2J5RKFQ5DB2XJANTDRM6FV5PS7VVAS7UZ"
POLICY_CONTRACT_ADDRESS = "CCVIGBDNOA2NVOYBZF5HN2GLQEQUAQX2MG3EXNCK2OF3WTGBPLAGDGMO"
ASSETS_WASM_HASH = "some_assets_wasm_hash"
SLACK_DEFAULT_URL = "some_slack_default_url"
BLOCKCHAIN_URL = "some_blockchain_url"
NETWORK_PASSPHRASE = "some_network_passphrase"
